# Introdução Numpy


In [1]:
from platform import python_version
print('Versão do Python: ', python_version())

Versão do Python:  3.10.12


In [2]:
import numpy as dsa
dsa.__version__

'1.26.4'

In [ ]:
# Introdução para instalar uma versão exata do pacote em python
# !pip install nympy==1.22.2

### Criando Arrays NumPy

In [6]:
# Array criado a partir de uma lista python
arra1 = dsa.array([10, 21, 32, 43, 48, 15, 73, 57, 89])

In [7]:
print(arra1)

[10 21 32 43 48 15 73 57 89]


In [9]:
type(arra1)

numpy.ndarray

In [10]:
arra1.shape

(9,)

Um array NumPy é uma estrutura de dados multidimencional usada em computação científica e análise de dados. O NumPy fornece um objeto de matriz N-dimensional (ou ndarray), que é uma grande homogênea de elementos, geralmente números, que podem ser indexados por um conjunto de inteiros.os arrays NumPy são mais eficientes do que as listas Python para armazenar e manipular grandes quantidades de dados, pois sãio implementados em Linguagem C e fornecem várias otimizações de desempenho. Além disso, o NumPy permite a fácil leitura e escrita de arquivos de dados, integração com outras bibliotecas Python e suporte a operações em paralelo usando várias CPUs pu GPUs. 


In [11]:
# imprimindo uim elemento específico no array
arra1[4]

48

In [12]:
#indexação
arra1[1:4]

array([21, 32, 43])

In [13]:
#indexação
arra1[1:4+1]

array([21, 32, 43, 48])

In [14]:
# Cria uma lista de índices
indices = [1, 2, 5, 6]

In [15]:
# Imprimindo os elementos dos indices
arra1[indices]

array([21, 32, 15, 73])

In [16]:
# cria uma máscara booleana para os elementos pares
mask = (arra1 % 2 == 0)

In [17]:
arra1[mask]

array([10, 32, 48])

In [18]:
# alterando um elemento no array
arra1[0] = 100

In [19]:
print(arra1)

[100  21  32  43  48  15  73  57  89]


In [20]:
# Não é possível incluir elementos de outro tipo
try:
    arra1[0] = "Novo Elemento"
except Exception as e:
    print('Operação não é permitida')
    for i in e.args:
        print(i)

Operação não é permitida
invalid literal for int() with base 10: 'Novo Elemento'


## Funções NumPy

In [21]:
# Função np.array() cria um array numpy
arr2 = dsa.array([1, 2, 4, 5])

In [22]:
print(arr2)

[1 2 4 5]


In [23]:
# Verificando o tipo do objeto
type(arr2)

numpy.ndarray

In [24]:
# Usando métodos do array numpy
arr2.cumsum()

array([ 1,  3,  7, 12])

In [25]:
arr2.cumprod()

array([ 1,  2,  8, 40])

In [ ]:
# digite . e pressione a tecla tab no seu teclado para visualizar as funções para minipular objetos numpy
dsa

In [27]:
# A função arange cria um array numpy contendo uma progressão aritimética a partir de um intervalo - start, stop, step
arra3 = dsa.arange(0, 50, 5)

In [28]:
print(arra3)

[ 0  5 10 15 20 25 30 35 40 45]


In [29]:
type(arra3)

numpy.ndarray

In [30]:
# formato do array
dsa.shape(arra3)

(10,)

In [31]:
print(arra3.dtype)

int64


In [32]:
# cria um array preenhido com zeros
arr4 = dsa.zeros(10)

In [33]:
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
# Retorna 1 nas posições em diagonal e 0 no restante
arr5 = dsa.eye(3)

In [4]:
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# os valores passados  como parâmetro, forman uma diagonal
arr6 = dsa.diag(dsa.array([1, 2, 3, 4]))

In [6]:
print(arr6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [8]:
# Array de valores booleados
arr7 = dsa.array([True, False, False, True])

In [9]:
print(arr7)

[ True False False  True]


In [10]:
# Array de strings
arr8 =  dsa.array(['Linguagem Python', 'Linguagem R', 'Linguagem Julia'])

In [11]:
print(arr8)

['Linguagem Python' 'Linguagem R' 'Linguagem Julia']


A função linspace() do numpy é usada para criar uma sequência de nũmeros igualmente espaçados dentro de um intervalo especificado. Essa função é amplamente utilizada em programação científica e matemática para gerar arrays de numeros para diversos fins, como gráficos, cálculos e simulações.
O método linspace (linerarly vector) retorna um número de valores igualmente distribuídos no intervalo específicado.

In [12]:
print(dsa.linspace(0 ,10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [13]:
print(dsa.linspace(0, 10, 15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


A função logspace() do numpy é usada para criar uma sequência de números igualmente espaçados em escala logarítica dentro de um intervalo especificado. Essa função é amplamento utilizada em programação científica e matemática para gerar arrays de números para diversos fins, como gráficos, cálculos e simulações.

In [15]:
print(dsa.logspace(0, 5, 10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]


###Manipulando Matrizes

In [17]:
# Criando uma matriz
arr9 = dsa.array([[1, 2, 3], [4, 5, 6]])

In [18]:
print(arr9)

[[1 2 3]
 [4 5 6]]
